### ISSUE TITLE
Unable to read highly compressed data using BZIP2 filter id 307

### ISSUE THREAD

**Issue by nhz2** [h5wasm/h5wasm-plugins#10]
### Describe the bug

Unable to read highly compressed data using BZIP2 filter id 307

### To Reproduce

I created a .h5 file using the Python script:

```python
import numpy
import h5py
import hdf5plugin

# create a .h5 file with the bzip2 plugin on easily and not easily compressable data
f = h5py.File('test.h5', 'w')
f.create_dataset('arange10', data=numpy.arange(10), compression=hdf5plugin.BZip2())
f.create_dataset('zeros', data=numpy.zeros(10000), compression=hdf5plugin.BZip2())
f.close()
```

[test.zip](https://github.com/user-attachments/files/22181884/test.zip)

[test.h5](https://github.com/user-attachments/files/22245407/test.txt)

Then I used the following HTML and `python3 -m http.server 8000`

```html
<!DOCTYPE html>
<html>
  <head>
    <script type="module">
      import h5wasm from "https://cdn.jsdelivr.net/npm/h5wasm@0.8.3/dist/esm/hdf5_hl.js";
      import {
        plugin_names,
        install_plugins,
      } from "https://cdn.jsdelivr.net/npm/h5wasm-plugins@0.1.1";

      const module = await h5wasm.ready;
      const { FS } = module;
      await install_plugins(module, plugin_names);

      const response = await fetch(
        "test.h5"
      );
      const buffer = await response.arrayBuffer();
      FS.writeFile("test.h5", new Uint8Array(buffer));

      const file = new h5wasm.File("test.h5", "r");
      const dataset = file.get("arange10");
      console.log(dataset);
      console.log(dataset.value);
      const zeros_dataset = file.get("zeros");
      console.log(zeros_dataset);
      console.log(zeros_dataset.value);
    </script>
  </head>
  <body></body>
</html>
```

In the console, I get:

```
hdf5_util.js:9 Uncaught TypeError: resolved is not a function
    at stubs.<computed> (hdf5_util.js:9:3911868)
    at libH5Zbz2.so.H5Z_filter_bzip2 (libH5Zbz2.so-0004c48a:0x803)
    at 00b24902:0x2de15
    at 00b24902:0x4045e
    at 00b24902:0x12ce45
    at 00b24902:0x78366
    at 00b24902:0x171eda
    at 00b24902:0xc74e8
    at 00b24902:0xc670a
    at 00b24902:0x12bb67
```

`at libH5Zbz2.so.H5Z_filter_bzip2 (libH5Zbz2.so-0004c48a:0x803)`

refers to `call $realloc`

I suspect that the zeros are highly compressed, thus when decompressed, `realloc` is called in:
 https://github.com/HDFGroup/hdf5_plugins/blob/61e2c328814e44d25dba6baa8da0beaaf1c331a4/BZIP2/src/H5Zbzip2.c#L188

and this is not working on the web version of the filter.

**Comment by bmaranville** [comment]
I think this is now working - I updated my tests to user larger arrays as you did, and was able to reproduce the issue.  I added `realloc` and `strcpy` and now tests with `bzip2` filter and large datasets pass.

Please update your `h5wasm` to version 0.8.5.

**Comment by nhz2** [comment]
Yes, this works with 0.8.5 for me. Thank you for fixing this.
